### ISSUE TITLE
no compile

### ISSUE THREAD

**Issue by josep112** [150balbes/Amlogic_s905#11]
Hello
I'm trying to compile but nothing happens could you help me?

mkimage -A arm -O linux -T script -C none -d s905_autoscript.txt s905_autoscript
Image Name:   
Created:      Wed Sep 13 08:34:51 2017
Image Type:   ARM Linux Script (uncompressed)
Data Size:    468 Bytes = 0.46 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 460 Bytes = 0.45 kB = 0.00 MB

**Comment by 150balbes** [comment]
Hi
1. The build went without errors. 
2. If the script does not work, then in the template (s905_autoscript.txt) given the right parameters, or u-boot does not support such parameters.
