### ISSUE TITLE
How to enable update mode in Ubuntu Server?

### ISSUE THREAD

**Issue by free-14** [150balbes/Amlogic_s905#14]
I created a USB flash with the image for vim2. But I have an ubuntu server installed on emmc. How do I enable the update mode for what would have been downloaded from the flash card?
In the second paragraph, this is not described. https://github.com/150balbes/Amlogic_s905/wiki/s905_multi_boot

**Comment by 150balbes** [comment]
What is the exact firmware version installed to eMMC ? There is a possibility to connect the console UART ?

**Comment by free-14** [comment]
The latest version of Ubuntu Server is installed. VIM2_Ubuntu-server-16.04_Linux-4.9_V170922.  Do you mean this? http://docs.khadas.com/develop/SetupSerialTool/ . Yes, I can do it. But is it possible to do this from the console server without UART?

**Comment by 150balbes** [comment]
You can try without UART console, through the terminal. Check for commands from the root user "fw_printenv"

**Comment by free-14** [comment]
В итоге я прописал скрипт в ручную, через UART.  тема закрыта.
