### ISSUE TITLE
VIM2 + Ubuntu server on emmc \\ microsd for backup memory emmc (ubuntu server all) \\ restore from backup microsd to emmc.

### ISSUE THREAD

**Issue by free-14** [150balbes/Amlogic_s905#15]
Is it possible to create such a project on this model? If there is an opportunity to contact you in Russian I will be very happy.

**Comment by 150balbes** [comment]
Такая утилита уже давно есть в составе Armbian (это утилита "ddbr"). Она позволяет создать полную резервную копию на внешний носитель (SD или USB) и восстановить ее в полном виде (вместе с загрузчиком и всеми разделами "как есть" на момент создания копии) обратно при сбоях или экспериментах. Таких копий можно делать сколько угодно. Кстати, на этом принципе основана установка моих прошивок MultiOS_3_in_1 и прочих с сайта - это копии рабочей системы с реальной железки.

**Comment by free-14** [comment]
Это все здорово. Но вот конкретного описания реализации этого всего для khadas vim2 я не нашел. Да я читал у вас в github. Но как работать с загрузчиком vim2 нет .все разбросано по форумам. И собирать по кускам не хотел. А вдруг убью железку.

**Comment by 150balbes** [comment]
Страница на вики устарела, я ее удалил.
Сейчас утилита ddbr сильно изменилась и упростился порядок работы с ней.
Теперь это штатная утилита во всех образах Armbian.
То бишь активируется мультизагрузка, запускается Armbian с внешнего носителя и от root выполняется команда "ddbr". Дальше по подсказкам. Первый этап - создать резервную копию eMMC. При наличии резервной копии, можно в любой момнет восстановить состояние eMMC (всей системы) на момент создания копии. В обычных условиях (если самому не ломать загрузчик), для создания копии и восстановления, можно использовать любой , подходящий по размеру, носитель - SD или USB. Важно обеспечить качественный носитель (что-бы файл копии на нём не стал битым), для этого его можно дополнительно сохранить на ПК или другие носители (с контрольной суммой, в архиве и прочее). Если сломали u-boot, тогда придётся выполнить несколько дополнительных шагов для установки на SD карту нужной версии u-boot (что-бы можно было запустить систему с внешнего носителя при испорченом u-boot в eMMC). А уже из запущенной с внешнего носителя системы - можно всё легко восстановить.

**Comment by free-14** [comment]
Спасибо. Но если честно вначале было не понятно откуда и что запускать. Но вроде разобрался. Вопрос: 1. Загрузка (в armbian) с microsd (если она в слоте microsd) не происходит, только с USB. так же backup не делается на microsd (в слоте microsd) он ее не видит. Видит только sd1 sd2. 
2. Нашел описание как установить на emmc http://4pda.ru/forum/index.php?showtopic=807415&st=220#entry67120538 но вот этот образ kvim2_update_SRC_20170926.img.xz не хочет загружаться. А вот обычным linux с ядром 4.9 отлично загрузился.

**Comment by 150balbes** [comment]
1. Создание копии и восстановление возможны только при запуске системы с внешнего ноителя (поэтому утилита ddbr удалена из системы на eMMC), идёт полная перезапись внутренней памяти. ddbr работает по тому же принципу, что клонезила. Что-бы удалённо перезаписать системы - нужно писать совсем другой сценарий, который будет работать из запущенной системы с перемонтирование разделов на лету и много чего еще учитывать.

2. Не понял, в чем вопрос про консольный образ ? Этот образ уже не актуален (удалён). Во всех последних образах Armbian есть все утилиты - ddbr, kvim2-update, kvim-update. Можете использовать.

**Comment by free-14** [comment]
По второму вопросу только то что не подходит пароль и логин.
