### ISSUE TITLE
4.9.40 Kernel module CIFS not found

### ISSUE THREAD

**Issue by free-14** [150balbes/Amlogic_s905#16]
Как добавить в это ядро модуль cifs?

**Comment by 150balbes** [comment]
Он уже есть
https://github.com/150balbes/Amlogic_s905-kernel/blob/khadas-4.9/config_20180127#L4266

**Comment by free-14** [comment]
Но почему я его не наблюдаю.
~# find /lib/modules/`uname -r` -name '*.ko' (нет cifs.ko)
~# modprobe cifs
modprobe: FATAL: Module cifs not found in directory /lib/modules/4.9.40

**Comment by free-14** [comment]
Возможно как то его включить? или обновить ядро, ( https://linuxthebest.net/kernel-ubuntu-16-04/ ) не будет ли потом проблем с загрузчиком ?

**Comment by 150balbes** [comment]
Вы можете собрать свою версию ядра (со своим конфигом) и в ручную установить его в систему.

**Comment by 150balbes** [comment]
В версии 4.9.40 20180315 модуль точно есть.

**Comment by free-14** [comment]
Как мне установить во внутреннюю память eMMC Armbian_5.41_S9xxx_Ubuntu_xenial_4.9.40_server_20180315.img.xz (этот архив XZ) ?
Я нашел единственную статью http://4pda.ru/forum/index.php?showtopic=807415&view=findpost&p=67120538 где вы говорите как установить на eMMc вот с этим архивом https://yadi.sk/d/9DLFNLXA3N726n/VIM2_Ubuntu-server-16.04_Linux-4.9/20171025 через /ddbr /restore. Вы как то очень коротко объясняете))) подводных камней очень много по незнанке.))

**Comment by 150balbes** [comment]
Эта статья о другом варианте установки готовой системы.
Для Armbian используется свой алгоритм. Обращаю внимание - установка идёт в существующие разделы от андройда. Поэтому, если у вас не стандартный вариант родного андройда (прошивки) возможны разные глюки и придётся часть работы делать руками.
1. Обязательно создать (через утилиту ddbr) перед установкой полную копию внутреннего содержимого eMMC (что-бы восстановиться при любых не штатных событиях).
2. Для установки в eMMC используется скрипт /root/install.sh , который запускается от имени root. После того как он отработает, выключаем ТВ бокс, вытаскиваем носитель и пробуем запуск без него.
3. Если для запуска с внешнего носителя не используется файл dtb.img, то вероятность удачного запуска из eMMC существенно выше. Если используется, то возможно при попытке запуска система не запуститься. Тогда нужно опять запустить систему с того же самого носителя (не меняя dtb на нём) и повторно запустить скрипт установки.
4. Если и после повторной установки не заработает из eMMC - придётся разбираться в чём причина (не правильные разделы, не хватает модулей в initrd для вашего типа памяти и т.д.).
