### ISSUE TITLE
8021q VLAN module

### ISSUE THREAD

**Issue by Sparkxxx** [150balbes/Amlogic_s905#17]
Hi and thanks for your work,

2 quick questins please:
1. I am currently running uname -a
Linux amlogic 3.14.29 #146 SMP PREEMPT Tue Dec 26 12:40:49 MSK 2017 aarch64 aarch64 aarch64 GNU/Linux s912
When I try to sudo modprobe 8021q
modprobe: FATAL: Module 8021q not found in directory /lib/modules/3.14.29
I installed VLAN package but it can't find whatever it can't find, I'm not very into kernels these days.
Is there anything quick that I should do to get this working?

2. Would I have more luck with these images to get the VLANs working?
Armbian_5.41_S9xxx_Ubuntu_xenial_4.9.76_icewm_20180219.img.xz
Armbian_5.37_S9xxx_Ubuntu_xenial_4.9.40_server_20180204.img.xz

Spasiba balshoi

**Comment by 150balbes** [comment]
> Is there anything quick that I should do to get this working?
To build a new kernel with this option.

> Would I have more luck with these images to get the VLANs working?
These kernels do not have this module.
