### ISSUE TITLE
It's not load

### ISSUE THREAD

**Issue by Slonik** [150balbes/Amlogic_s905#18]
Здравствуйте!
Приставка под названием X96, внутри процессор S905X, память 1Гб+8Гб. На плате маркировка Q5X V2.1
Делаю все как написано, пробую грузиться и с SD и с флешки - бесполезно, заставка, на флешке лампочка мигает недолго и всё висит. Пробовал разные ваши прошивки.
Помогите пожалуйста куда копать, очень нужен Armbian (сервер).

**Comment by 150balbes** [comment]
Судя по симптомам, нужно подобрать правильный dtb (скопировать в корень и переименовать в "dtb.img"). Какие пробовали ?

**Comment by Slonik** [comment]
Простите за мою тупизну, а где их скачать?

**Comment by 150balbes** [comment]
Ни чего скачивать не нужно. После записи образа на носителе есть каталог /dtb, в нём набор разных файлов dtb для разных моделей. Если точно не знаете какой от вашей модели, просто по очереди копируете все , где есть указание p212 , это обозначение платформы s905x, переименовать в dtb.imig, попробовать запустить. Если не сработало, пробуете другой и так по очереди пробуете пока не найдёте нужный.

**Comment by Slonik** [comment]
А там два каталога: dtb и dtb с номером версии. Откуда правильнее копировать файл?

**Comment by 150balbes** [comment]
без разницы, это одно и тоже, каталог dtb - для текущей версии ядра (это актуально, если используется несколько вариантов ядра)

**Comment by Slonik** [comment]
Спасибо, добрый человек! Пусть удача сопутствует тебе всегда в твоих добрых делах!

**Comment by Slonik** [comment]
Посмотрел на плату, там WiFi чип 8189ETV
