### ISSUE TITLE
DTB for MXQ Pro 4K (based on S905W)

### ISSUE THREAD

**Issue by mashed-potatoes** [150balbes/Amlogic_s905#20]
Привет, купил бокс на основе S905W, но не могу найти под него нормальный dtb. Нигде не работает все 4 порта, только первый + WiFi тоже не работает. Этот бокс не совпадает с характеристиками в шапке 4pda.
Оригинальный dtb (потерян): `???_p218.dtb`
Шасси: `MXQ_S95W_V2.0`
RAM/ROM: 1GB/8GB
Wi-Fi: SV6051P
**Спасибо ;)**

**Comment by 150balbes** [comment]
Привет. А в чём суть вопроса ?

**Comment by mashed-potatoes** [comment]
`не могу найти под него нормальный dtb` - проблема решена, нашел dtb у проекта AlexELEC. В след. сборках можешь добавить файлы [отсюда](https://github.com/AlexELEC/S905-trees/tree/master/S905W)
Удачи)
