### ISSUE TITLE
If it's possible to install other linux distros on s905?

### ISSUE THREAD

**Issue by yangxuan8282** [150balbes/Amlogic_s905#21]
I have an android box (phicomm N1, which use s905), and it work pretty well with your Armbian and opensuse image. And I think it maybe possible run more distros on it, what I did is use your image, delete everything else except `/boot`, `/lib/firmware`, `/lib/modules`, then copy new rootfs into it.
For now, I have tried alpine aarch64, the kernel is from `S9xxx_openSUSE_LXQT_20170517_3_14.img.xz`, it boot although no HDMI output ( just blackscreen ), but I can ssh into it and install package. Used to got blackscreen issues on odroid xu4, which turn out need uncomment HDMI config from it's `boot.ini`, but I didn't found it on the opensuse image in `/boot`, so would you mind give some suggestion?

**Comment by 150balbes** [comment]
The /boot section has a script "hdmi.sh". Add it to run in " rc.local" or make a run through the "service". Examples of how this can be done, you can find the images Armbian\OpenSUSE\ArchLinux etc. Or use the latest version of the kernel "4.18", in it HDMI works automatically immediately at startup.

**Comment by yangxuan8282** [comment]
Today I tried run deepin arm64 on the box, use 3.14.29 and 4.18.0 kernel, both of them can boot, but there are some display issues.
For 3.14, the sound work, the monitor is 1080p, the output from `xrandr` also report the system use 1080p, but it actually only display part of screen( about 1/4 ), and by press `Win` button can launch app launcher.

For 4.18, the N1 box chip is s905D, I use device tree file `meson-gxl-s905d-p230.dtb` , the sound effect not work, and the display is also kind of weird, the app launcher is really small. 

the deepin rootfs I used is this one: https://github.com/yangxuan8282/gen-rpi_os/releases/download/rpi/deepin-rpi-aarch64.zip

below is the screenshot of 4.18.0

![deepinscreenshot_20180914115152](https://user-images.githubusercontent.com/6976464/45528909-20dd5400-b815-11e8-9674-fb4954db920c.png)

**Comment by 150balbes** [comment]
> There is another problem, how do you create the partition for img?

 To extend a partition use the checked versions of the scripts from Armbian or Libreelec. On these systems, these scripts work perfectly with all types of media (SD and USB).



> seems after it run, the system can't boot into system anymore. I guess it broke the partition, but don't know it affect which part.

When you recreate a partition, you lose the important part-the partition label, which is used to start the system in startup scripts.



> For 3.14, the sound work, the monitor is 1080p, the output from `xrandr` also report the system use 1080p, but it actually only display part of screen( about 1/4 ), and by press `Win` button can launch app launcher.

The procedure for changing the kernel screen resolution 3.14 is described here.
https://forum.armbian.com/topic/2419-armbian-for-amlogic-s905-and-s905x/


> For 4.18, the N1 box chip is s905D, I use device tree file `meson-gxl-s905d-p230.dtb` , the sound effect not work, and the display is also kind of weird, the app launcher is really small (it should cover fullscreen), the desktop look normal.

For the sound to work you need to collect your version of dtb. It is possible to operate the screen as desired changes in the dtb. Or the behavior of the screen is affected by the settings from the RPi.

**Comment by yangxuan8282** [comment]
Just found why the 4.18 kernel display weird on deepin arm64, the xrandr reports there are two monitor connected:

```bash
pi@raspberrypi:~$ DISPLAY=:0 xrandr
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 3840 x 2160
Composite-1 connected (normal left inverted right x axis y axis)
   720x576i      50.00
   720x480i      59.94
HDMI-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 708mm x 398mm
   1920x1080     50.00*+  60.00    60.00    59.94    30.00    24.00    29.97    23.98
   3840x2160     30.00    25.00    24.00    29.97    23.98
   1920x1200     59.95
   1920x1080i    60.00    50.00    59.94
   1600x1200     60.00
   1680x1050     59.88
   1280x1024     60.02
   1440x900      59.90
   1280x800      59.91
   1280x720      60.00    50.00    59.94
   1024x768      60.00
   800x600       60.32
   720x576       50.00
   720x480       59.94
```

Besides the HDMI, there is another `Composite-1`, and the OS think it is primary display, but actually it not exist ( this android box only have one HDMI output). Not sure how this happen, but after select `HDMI-1` as primary display, the system look normal now. 

And as for my auto resize scripts, I found the reason why after execute it the system was broken, after input `n`, `p`, `2`, it will recreate second partition, but there is some space before the first partition ( before 8192 ), so if just press `enter` it will create the second partition before the first one, obviously this will not work, I should input `270336` as start of new one instead of use default ( which is 2048 for fdisk ).

**Comment by yangxuan8282** [comment]
@150balbes 
hi, would mind explain how to build u-boot and install it?
From this file https://github.com/150balbes/Build-Armbian/blob/c50c4ebc13e81b3a72dc2ba05d722b1e3edaf767/config/sources/aml-s9xxx.conf , seems you use https://github.com/150balbes/u-boot.git and this tag tag:vim2.01
but I didn't found which config file to use for compile s9xxx u-boot
and from this line: https://github.com/150balbes/Build-Armbian/blob/c50c4ebc13e81b3a72dc2ba05d722b1e3edaf767/config/sources/aml-s9xxx.conf#L116 , seems the command to install u-boot is 

```
    	dd if=$1/u-boot.bin of=$2 bs=1 count=442 conv=fsync > /dev/null 2>&1
    	dd if=$1/u-boot.bin of=$2 bs=512 skip=1 seek=1 conv=fsync > /dev/null 2>&1
```

**Comment by 150balbes** [comment]
config
https://github.com/150balbes/Build-Armbian/blob/c50c4ebc13e81b3a72dc2ba05d722b1e3edaf767/config/boards/aml-s9xxx.conf#L4

**Comment by yangxuan8282** [comment]
thanks, I can create own linux image now

**Comment by yangxuan8282** [comment]
@150balbes 
thanks, I create an alpine image with this [scripts](https://github.com/yangxuan8282/gen-rpi_os/blob/master/gen-alpine_n1.sh) for s905d (should also work for other s9xxx, just need to move dtb to `/boot/dtb.img`): https://github.com/yangxuan8282/phicomm-n1/releases/download/alpine/2018-09-18-alpine-n1-aarch64.zip

The kernel apk APKBUILD is [here](https://github.com/yangxuan8282/phicomm-n1/blob/master/kernel/alpine/APKBUILDs/linux-s905d/APKBUILD), use your https://github.com/150balbes/Amlogic_s905-kernel ,and [config_20180719](https://github.com/150balbes/Amlogic_s905-kernel/blob/master/config_20180719), except wifi most things work.  To make wifi work I need to restart wpa_supplicant once, maybe the modules load after wpa_supplicant. From the dmesg output, the phicomm N1 use same driver as raspberry pi 3B+, so I guess them use same chip (CYW43455). Still need time to find why this happen.

**Comment by 150balbes** [comment]
Try adding the correct 'firmware' to your WiFi

**Comment by yangxuan8282** [comment]
the firmware for CYW43455 is `/lib/firmware/brcm/brcmfmac43455-sdio.bin`, it was include in alpine package `linux-firmware-brcm`, the wifi work , but need to restart wpa_supplicant after every boot

the dmesg about wifi on raspberry pi 3b+

```bash
pi@raspberrypi:~ $ dmesg | grep brcmfmac
[    3.511115] brcmfmac: F1 signature read @0x18000000=0x15264345
[    3.517913] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43455-sdio.bin for chip 0x004345(17221) rev 0x000006
[    3.518287] usbcore: registered new interface driver brcmfmac
[    3.808983] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[    3.809796] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 9.10.105 Compiler: 1.29.4 ClmImport: 1.36.3 Creation: 2018-03-09 18:56:28
[    6.786138] brcmfmac: power management disabled
```

dmesg on phicomm n1:

```bash
┌─[n1@phicomm]─[~]
└──╼ $ dmesg | grep brcmfmac
[    9.116149] brcmfmac: F1 signature read @0x18000000=0x15264345
[    9.118915] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    9.119391] usbcore: registered new interface driver brcmfmac
[   11.353514] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[   11.401566] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
```

the firmware already exist on n1:

```bash
┌─[n1@phicomm]─[~]
└──╼ $ ls /lib/firmware/brcm/brcmfmac43455-sdio.*
/lib/firmware/brcm/brcmfmac43455-sdio.bin       /lib/firmware/brcm/brcmfmac43455-sdio.txt
/lib/firmware/brcm/brcmfmac43455-sdio.clm_blob
``` 

I'm not sure if there are any other driver conflict with brcmfmac.

and seems with 4.18 kernel the Ethernet ( RTL8211F , which is same as odroid c2 ) is not really stable, it  will lose connect after hours (usually happen when I copy hundred MB big file ), not sure which kernel config related to this NIC

**Comment by yangxuan8282** [comment]
seems I have found where the problem is, to make wifi (CYW43455) work, just add `btsdio` to blacklist:

```
echo "blacklist btsdio" | tee -a  /etc/modprobe.d/blacklist.conf
```

it conflict with the wifi driver, so the wlan didn't init success, because it need sdio interfaces

and as for the wired connection, the chip rtl8211f seems not stable with default `drivers/net/phy/realtek.c`,  there is a patch in armbian rockchip build: https://github.com/armbian/build/blob/master/patch/kernel/rockchip-default/01-linux-0006-rtl8211f.patch , but that is for 4.4 kernel, don't know how to make it work in new 4.18.7

@150balbes have you ever tried pxe boot s9xxx like [this](https://wiki.odroid.com/odroid-xu4/application_note/software/pxe_boot)? the u-boot should able to do it, although still need use usb disk

**Comment by 150balbes** [comment]
I have not tried PXE , but after the tftp download of the kernel and other works.

**Comment by yangxuan8282** [comment]
the Ethernet not stable issues seems  related to EEE ( Energy-Efficient Ethernet ), after disable it the eth0 still  alive after copy big files and do some iperf test

```diff
diff --git a/arch/arm64/boot/dts/amlogic/meson-gxl-s905d-p230.dts b/arch/arm64/boot/dts/amlogic/meson-gxl-s905d-p230.dts
index a9f9bb9..96697c5 100644
--- a/arch/arm64/boot/dts/amlogic/meson-gxl-s905d-p230.dts
+++ b/arch/arm64/boot/dts/amlogic/meson-gxl-s905d-p230.dts
@@ -90,6 +90,7 @@
 	external_phy: ethernet-phy@0 {
 		compatible = "ethernet-phy-id001c.c916", "ethernet-phy-ieee802.3-c22";
 		reg = <0>;
+		eee-broken-1000t;
 		max-speed = <1000>;
 		interrupt-parent = <&gpio_intc>;
 		interrupts = <29 IRQ_TYPE_LEVEL_LOW>;
``` 

but the wifi seems still not reliable, and disable power management not help:

```diff
diff --git a/drivers/net/wireless/broadcom/brcm80211/brcmfmac/cfg80211.c b/drivers/net/wireless/broadcom/brcm80211/brcmfmac/cfg80211.c
index b6122aa..e2098ad 100644
--- a/drivers/net/wireless/broadcom/brcm80211/brcmfmac/cfg80211.c
+++ b/drivers/net/wireless/broadcom/brcm80211/brcmfmac/cfg80211.c
@@ -2697,6 +2697,8 @@ brcmf_cfg80211_set_power_mgmt(struct wiphy *wiphy, struct net_device *ndev,
 	 * preference in cfg struct to apply this to
 	 * FW later while initializing the dongle
 	 */
+	pr_info("power management disabled\n");
+	enabled = false;
 	cfg->pwr_save = enabled;
 	if (!check_vif_up(ifp->vif)) {
```

when copy file with `scp` with wlan0, the speed will drop from 7MB/s to hundred KB/s

**Comment by yangxuan8282** [comment]
@150balbes 
hi, I create a device tree for phicomm N1 based on `meson-gxl-s905d-p230.dts`
here is the patch for latest [commit](https://github.com/150balbes/Amlogic_s905-kernel/commit/0774525e710209a9e99136e5373b955f6c7defba) : https://github.com/yangxuan8282/phicomm-n1/blob/32edf55cd7a87ec7eac25d4280981100ae6e53d3/kernel/alpine/APKBUILDs/linux-s905d/add-phicomm-n1-device-tree.patch

remove sdcard and cvbs stuff, because this box seems don't support them

It support wifi, fix RTL8211F with disable EEE, don't have bluetooth support for now

If I create a pull request, do you have interest to merge it?

**Comment by 150balbes** [comment]
> If I create a pull request, do you have interest to merge it?

I can add such a change, but the problem will be that the next time I update the kernel sources, these changes may stop working. You'd better try adding a new dtb to the main kernel.

**Comment by yangxuan8282** [comment]
@150balbes 
There are two dtb file from you in mainline kernel, submit by superna9999.
Which way is better to create pull request about dtb file: create PR on github or send patch in mail list?
And I don't really have experience contribute to mainline, would you mind take a look at that [dtb](https://github.com/yangxuan8282/phicomm-n1/blob/32edf55cd7a87ec7eac25d4280981100ae6e53d3/kernel/alpine/APKBUILDs/linux-s905d/add-phicomm-n1-device-tree.patch) file if it is fit their standards.

**Comment by 150balbes** [comment]
I don't have much experience in creating patches to the core. Therefore, I recommend to contact the mailing list with this request, I think there experienced users will help.

**Comment by yangxuan8282** [comment]
@150balbes 
Thanks for your advise, I will get contact with related maintainer.
Before contact them, I need make sure it also work for mainline kernel. It seems like that device tree in your kernel is kind of different from upstream. Can I ask what's the source of your [150balbes/Amlogic_s905-kernel](https://github.com/150balbes/Amlogic_s905-kernel)? Seems like mainline kernel, maybe add some patches from superna9999, and some extra modification. And can we directly boot mainline kernel on s9xxx?

**Comment by superna9999** [comment]
@yangxuan8282 Hi, it's not so hard to push upstream, to start you can:
look at http://linux-meson.com/doku.php
register to the mailing list http://lists.infradead.org/mailman/listinfo/linux-amlogic
go on freenode `#linux-amlogic`
follow https://kernelnewbies.org/FirstKernelPatch and https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html
please don't hesitate sending a patch with questions, we will guide you if it needs reworking

**Comment by superna9999** [comment]
@yangxuan8282 vanilla (without any changes) linux mainline with defconfig boots fine

**Comment by superna9999** [comment]
@yangxuan8282 I have questions on your patch:
- are you sure it's s905d ? on the website it's clearly written "s905"
- is the device based on a Amlogic P230 reference design ? in this case you can follow the P230 dts and only change what diverges from the reference design

**Comment by yangxuan8282** [comment]
@superna9999 
thanks for the links
this device indeed is s905d, this [links](http://www.acwifi.net/4312.html) have some pictures about the box inside, some of them show the cpu details , guess their official website record wrong message

and yes, seems it is based on P230 reference design, we can boot it with device tree `meson-gxl-s905d-p230.dtb`, most things work except bluetooth, I need modified two section, disable EEE to make RTL8211F works, and remove cvbs (because this box not have composite, and keep it will affect display in some DE like deepin). To do this can I just define `&ethmac` in new device tree to overwrite original one? But as for remove cvbs, I don't know how to do it without create new device tree.

**Comment by yangxuan8282** [comment]
@superna9999 
this is the modified version phicomm n1 device tree as your suggest, based on P230 dts and only change what diverges from the reference design:

```
// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2018 He Yangxuan
 */

/dts-v1/;

#include "meson-gxl-s905d-p230.dts"

/ {
        compatible = "phicomm,n1", "amlogic,s905d", "amlogic,meson-gxl";
        model = "Phicomm N1";

        cvbs-connector {
                status = "disabled";
        };
};

&cvbs_vdac_port {
        status = "disabled";
};

&external_mdio {
        external_phy: ethernet-phy@0 {
                compatible = "ethernet-phy-id001c.c916", "ethernet-phy-ieee802.3-c22";
                reg = <0>;
                eee-broken-1000t;
                max-speed = <1000>;
                interrupt-parent = <&gpio_intc>;
                interrupts = <29 IRQ_TYPE_LEVEL_LOW>;
        };
};
```

tested work on 150balbes/Amlogic_s905-kernel

**Comment by yangxuan8282** [comment]
@150balbes 
hi, does this https://github.com/150balbes/u-boot/tree/2018 support `extlinux.conf`?

**Comment by superna9999** [comment]
@yangxuan8282 yes it's good

**Comment by superna9999** [comment]
@superna9999 Yes, the other people will give a review and you will eventually need to re-send an updated version with some fixes

**Comment by yangxuan8282** [comment]
@superna9999 
hi, I'm trying to figure out what should I do to send the patch according to the tutorial:

- fetch current source tree, that is https://git.kernel.org/pub/scm/linux/kernel/git/khilman/linux-amlogic.git here I guess, but I'm not sure should use master branch or amlogic-dt64-3 tag

- generate the patch based on source tree, describe the changes

it's something like this:

```
[PATCH] arm64: dts: meson-gxl: add support for phicomm n1

This patch adds support for the Phicomm N1. This device based on P230 reference design.
The phy is RTL8211F, need to disable Energy Efficient Ethernet (EEE) to make it stable.
And this box doesn't have cvbs, so disable related section in device tree.
```

- send the patch with mutt to linux-amlogic@lists.infradead.org and Cc to maintainer Carlo Caione <carlo@caione.org> && Kevin Hilman <khilman@baylibre.com>

Is that correct?

**Comment by superna9999** [comment]
Correct, let a few days for kevin & other reviewers to reply.

In any case, kevin won't apply it until 4.20-rc1 in 3 weeks time

**Comment by yangxuan8282** [comment]
@superna9999 
thanks, I have sent the patches to mailing list: http://lists.infradead.org/pipermail/linux-amlogic/2018-October/008490.html 
the content should be fine, but I should change `from` in my git send-email config to my name, so the mailing list display my email instead of my name, does this affect code review?

for now, how many distros support amlogic meson devices out of box? I tried archlinux arm, it's kernel is 4.18.14, and it's config include meson support, but it seems can't boot

with 150balbes kernel, I can boot centos7, alpine linux, debian stretch armhf/arm64, deepin, and should also work for most distros

**Comment by 150balbes** [comment]
> for now, how many distros support amlogic meson devices out of box? I tried archlinux arm, it's kernel is 4.18.14, and it's config include meson support, but it seems can't boot

Two small patches have already been added to my sources that allow you to run the mainline kernel on u-boot-2015 (which is used in all TV boxes and s9xxx devices). To run the mainline kernel, you need to either process it with the "mkimage" utility (this is very inconvenient for the subsequent automatic kernel update, you will have to add steps to process the kernel), or add patches.

**Comment by superna9999** [comment]
@yangxuan8282 You must do the distinction between which distro have a recent Linux arm64 with the right configs enabled to run on Amlogic SoCs, and others

Usually you can take any arm64 distribution, build your own kernel and run the distribution.

But for sure, OpenSuse Tumbletweed, Debian Testing (well, USB is missing, I opened a bug for that) & Arch Linux have the right kernel and configs to run it without any changes.

**Comment by yangxuan8282** [comment]
@superna9999  I have tried opensuse Tumbleweed on my s905d box, what I do is:
- download this img: http://download.opensuse.org/ports/aarch64/tumbleweed/images/openSUSE-Tumbleweed-ARM-JeOS-efi.aarch64-Current.xz , and flash it to usb storage with etcher(should same as dd)

- install u-boot with dd, the u-boot I used is from https://github.com/150balbes/u-boot/tree/vim2.02 , config file is https://github.com/150balbes/u-boot/blob/vim2.02/configs/khadas-vim2_defconfig

insert the usb disk into box, it just boot to android

also tried archlinuxarm:

- download ArchLinuxARM-aarch64-latest.tar.gz

- create two partition on usb disk, first one is fat, the second one is ext4, extract the tarball into the disk, mv the /boot/* to first partition

- create aml_autoscript and s905_autoscript with `mkimage`, add `uEnv.ini`, just like 150balbes did in his img

- flash the u-boot with dd

the hdmi seems into a turn on and turn off loop, and the system didn't boot

**Comment by 150balbes** [comment]
> insert the usb disk into box, it just boot to android

On u-boot-2018 in s912 while start with USB (writes that the wrong power supply) does not work, use the SD card.

**Comment by yangxuan8282** [comment]
@150balbes 
this s905d box don't have sd card slot, only two usb port
guess maybe should try pxe boot (tftp booting)

I create a `aml_autoscript.cmd` like this:

```
setenv kernel_addr "0x11000000"
setenv initrd_addr "0x13000000"
setenv dtb_mem_addr "0x1000000"

setenv serverip 192.168.2.101
setenv ipaddr 192.168.2.105

setenv bootargs "root=/dev/nfs nfsroot=${serverip}:/nfsshare/root,vers=3 rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 rootwait"

setenv bootcmd_pxe "tftp ${kernel_addr} vmlinuz-s905d; tftp ${dtb_mem_addr} dtb.img; tftp ${initrd_addr} uInitrd;"
run bootcmd_pxe
```

and use mkimage create u-boot script, cp the `aml_autoscript` into it

install u-boot (tried tags vim2.01 and vim2.02, from Makefile it is 201807) with `dd`

but this not work as except, guess this `aml_autoscript` is not acceptable by u-boot

**Comment by 150balbes** [comment]
How did you build u-boot ? For your model need to try the option for s905x. Try this option.

https://disk.yandex.ru/client/disk/Aarch64/Khadas/U-Boot/2018/VIM

**Comment by yangxuan8282** [comment]
@150balbes the previous u-boot config I use is khadas-vim2_defconfig
and just tried vim u-boot in your yandex disk, it still not work
do you have a working u-boot scripts (aml_autoscript or anything else) for tftp booting?

**Comment by yangxuan8282** [comment]
@superna9999 
I tried pxe boot debian testing with it's own kernel (linux-image-arm64), it still can't boot on the box, it just reboot

**Comment by ncopa** [comment]
> @ncopa @clandmeter do you have interest add amlogic meson support for alpine linux?

I don't think we have capacity to maintain a special kernel or kernelconfig for it. But I don't mind adding it to Alpine if someone else does the maintenance.

**Comment by superna9999** [comment]
@ncopa Having all the necessary kernel configs & DT for amlogic SoCs would be a great start !

**Comment by yangxuan8282** [comment]
@ncopa 
I can do the maintenance. This kernel actually is mainline kernel with some patches.

@superna9999 @150balbes 
According to the reply from alpine developer Natanael Copa ( he start the alpine linux ), I guess there are chance to add amlogic support into alpine upstream. With directly support from mainline kernel amlogic developer like @superna9999 , I think the alpine would be a great options for amlogic linux users.

I think we need do something:

- give a name of new kernel packeges, like linux-aml, linux-meson or something else

- decide should use mainline kernel add patches as sources, or still use Amlogic_s905-kernel from @150balbes 

- list which devices was supported by this kernel , maybe we should find some volunteer to test it, I just have a s905d box now

- add a pages in alpine linux wiki

- add amlogic device support in alpine u-boot packages

maybe we should discuss those in IRC or mailing list?

BTW, the mainline maintainer seems still not review my device tree, is this normal?

**Comment by 150balbes** [comment]
IMHO today in the main core has everything you need for basic support of AML S9xxx. And you can use official git Linux to build the system.

**Comment by superna9999** [comment]
@yangxuan8282 yes, it can take a few week, we are right before the linux merge window and there is some conferences taking all the time from maintainers

**Comment by yangxuan8282** [comment]
@ncopa @clandmeter
after discuss in linux-amlogic IRC, the new alpine amlogic kernel package will be `linux-amlogic`
and use mainline with patches from @superna9999 and @150balbes as sources, here is the new APKBUILD: https://github.com/yangxuan8282/phicomm-n1/blob/master/kernel/alpine/APKBUILDs/linux-amlogic/APKBUILD , I have tested it on my amlogic device
would you mind I ask why disable `IP_PNP` in `linux-rpi`: https://github.com/alpinelinux/aports/blob/master/main/linux-rpi/config-changes-rpi.armhf#L25
do I need to also disable this in `linux-amlogic`, and if the rest changes in `config-changes-rpi.armhf` is necessary to apply in other device?

**Comment by yangxuan8282** [comment]
@superna9999 @150balbes
This is a test build alpine img(no standard one, install some extra packages) with new [linux-amlogic](https://github.com/yangxuan8282/phicomm-n1/blob/master/kernel/alpine/APKBUILDs/linux-amlogic/APKBUILD) kernel:

https://github.com/yangxuan8282/phicomm-n1/releases/download/alpine_test_build/2018-10-24-alpine-amlogic-aarch64.zip

I can confirm the kernel work for my s905d box.

The img not install u-boot, and not include amlogic autoscript, just include a extlinux.conf

It can be installed with `dd` command.

Would you mind test it? 

The kernel package apply a offset patch from @150balbes: https://github.com/yangxuan8282/phicomm-n1/blob/master/kernel/alpine/APKBUILDs/linux-amlogic/offset.patch

about this patch, why need apply this patch, quote from @150balbes email:

> These patches are needed to run the kernel on Amlogic models that use the old version of u-boot (2015). Patches allow you to run the unprocessed" mkimage "kernel using the "booti" command. If you do not use patches, you can run the kernel with the "bootm" command, but you must first process the kernel with the "mkimage"utility. The utility adds its header to the kernel, which turns the kernel into an android format that the old u-boot (2015) can work with.

So, for the android box we need apply this offset patch and use amlogic autoscript for the amlogic u-boot on emmc. And for SBC like odroid c2, nanopi k2 and khadas vim we can add support in alpine u-boot package and use the alpine `extlinux.conf` : https://git.alpinelinux.org/cgit/aports/tree/main/u-boot/APKBUILD  

```
--- APKBUILD.orig
+++ APKBUILD
@@ -31,6 +31,9 @@
 aarch64) board_configs="
        thunderx:thunderx_88xx
        raspberrypi:rpi_3
+       khadasvim:khadas-vim,khadas-vim2
+       nanopi:nanopi-k2
+       odroid:odroid-c2
        ";;
 esac
```

**Comment by superna9999** [comment]
@yangxuan8282 Thanks for the work, I won't be able to test until a few days...

The offset patch is needed to boot from the amlogic u-boot version using the `booti` command, I have no idea why they enforced this, because mainline linux and mainline u-boot works perfectly with the standard offset.......... and it's a pain in the *** to keep this hack

For u-boot, yes it can be handy to have these boards support built, so we can use the built binary to either chainload from original u-boot or package it to replace the flashe u-boot.

**Comment by yangxuan8282** [comment]
@superna9999 @ncopa 
add amlogic support for alpine progress:

- kernel: have create PR for `linux-amlogic` : https://github.com/alpinelinux/aports/pull/5663

- u-boot: add odroid c2: http://lists.alpinelinux.org/alpine-aports/5768.html , will send patch for khadas.com vim and nanopi k2 after odroid c2 merged

the kernel package have been tested on my amlogic s905d box
