### ISSUE TITLE
Volumio ssv6051 Wifi not working on S905W

### ISSUE THREAD

**Issue by Hummtaro** [150balbes/Amlogic_s905#22]
Wifi is not working on my x96 with s905w in Volumio 1.0.
It works fine in your Armbian 5.44 build with same kernel.

It was looking for firmware in /usr/lib/firmware, so i linked that folder to /lib/firmware.
It can find firmware now but has a lot of sdio errors.

See [dmesg on pastebin](https://pastebin.com/M1s9NSZb).

I also tried to copy firmware and ssv6051.ko from your armbian into volumio with no difference..

**Comment by 150balbes** [comment]
Try replacing the Volumio kernel image and modules with firmware, take them from Armbian.

**Comment by Hummtaro** [comment]
I replaced kernel and modules+firmware with _3.14.29-aml-s9xxx-ge672901-dirty_ from armbian 5.44.
Does not change anything.. Maybe the problem is neither kernel nor firmware related.

I would try a 4.1* kernel from your newer builds but it looks like they don't support ssv6051 anyway?

**Comment by 150balbes** [comment]
There is no support for WiFi in kernel 4 yet.
