### ISSUE TITLE
Best tiny lunux distro

### ISSUE THREAD

**Issue by taravasya** [150balbes/Amlogic_s905#23]
Hello! Thanks for your awesome works!

I want to install Album Player on one of amlogic-distros for my **Mini M8s II** device(as I know its s905x). My question is: what most light linux version but with **alsa** enabled from all of your distros for amlogics? I think its must be something like Volumio, but I dont need mpd.

Thanks!!

**Comment by 150balbes** [comment]
Hi. The easiest is the server image. Alsa you can add, as usual, through "apt install". Alternatively, you can use Libreelec and disable KODI startup.

**Comment by taravasya** [comment]
Thank you for answear! I have two more question...

1)On yandex.disk in folder **Aarch64/Linux/Armbian/5.75/S905/deb** what files a store here? What I have to do with them?

2)On yandex.disk in folder **Aarch64/Libreeelec/Krypton-17/** we have file eg:
LibreELEC-S905_SD_USB.aarch64-17.6_20180122.img.gz 
and above:
LibreELEC-S905_SD_USB.aarch64-17.6_20180122.tar
what in second arhive? I see the same files and folders as on created SD card... Whats the point of this arhive?

Thank you!

**Comment by 150balbes** [comment]
1. Пакеты deb используются для локального обновления ядра (у кого уже работает прежний вариант Armbian). Если вы используете образы из этого каталога, вам ни чего не нужно делать с этими пакетами. 
2. Похоже вы мало знакомы с Libreelec. Это архив для обновления рабочей системы LE.

**Comment by taravasya** [comment]
То-есть и то и другое, в принципе одно и тоже, и в обоих случаях, если я использую образ из Ваших каталогов, то мне можно игнорировать эти доп.архивы?

**Comment by 150balbes** [comment]
Да.

**Comment by taravasya** [comment]
Подскажите, а есть ли x32 сборки для загрузки тв-боксов с карточки?

**Comment by 150balbes** [comment]
Нет, только aarch64. Комбинированый вариант , ядро 64 и система 32 бита, есть только LE (в имени указано arm) или Volumio
