### ISSUE TITLE
Find old mirror

### ISSUE THREAD

**Issue by Tao173** [150balbes/Amlogic_s905#27]
Hello, thanks for this interesting project. I use phicomm N1. I know from the Internet that Armbian_5.91_Aml-g12_Debian_buster_default_5.2.1_20190724.img.xz is very suitable for my machine. In the latest image, the system load is too high and Bluetooth can’t It works, but I can't find the old mirror. Could you please give me this mirror?

**Comment by 150balbes** [comment]
Old mirrors don't exist
