### ISSUE TITLE
H96 plus universal multiboot

### ISSUE THREAD

**Issue by aymenjemli** [150balbes/Amlogic_s905#4]
in fact i tried every version and it just dont work with h96 plus model or X92 ! Can you help please and give me exact procedure. 

thank you

**Comment by 150balbes** [comment]
Describe the steps that You make.10.12.2016, 02:14, "Aymen J." <notifications@github.com>:in fact i tried every version and it just dont work with h96 plus model or X92 ! Can you help please and give me exact procedure.
thank you

**Comment by aymenjemli** [comment]
i used the universal uboot file s905_uboot_multi_version_v2.zip
same as described : acces update + select file + uptodate. 
I tested to boot with usb flash disc not sd card. 

Maybe boot is ok but the problem came from the linux i want to use : ubuntu-14.04-headless-arm64.img

every time the box restart it shows message "unable to mount /misc!" and the second reboot is like nothing has been saved for the boot. 

Thank you Balbes :)

**Comment by 150balbes** [comment]
1. I recommend you to update-boot to the latest version. Files for activation can be downloaded here.
https://yadi.sk/d/XHEJwdLTsWJoH

2. What kind of image You want to use ? What files are in the first FAT partition of this image ?

3. To check the operation of the multi-boot, try any of the images here.
https://yadi.sk/d/5_32km_EsCV2A

4. In these topics you can find a lot of useful information.

http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/s905/tronsmart-ac/firmware-roms-tools-at/565449-running-linux-from-sd-card-or-usb-flash-drive-using-balbes150-method-and-files

http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/s905x/598320-a95x-s905x-emmc-boot-for-ubuntu

https://forum.armbian.com/index.php/forum/16-amlogic/

**Comment by aymenjemli** [comment]
Hello again balbos, 

I couldnt do it on H96 so i'm trying on MXQ PRO. 

But with your method i dont see on android the select button to choose file for update.

**Comment by 150balbes** [comment]
Need to open the applications list. There should be an app "Update&Backup". This application needs to run. It has a category of "Local update". You need to connect the prepared SD card and choose as archive to update the file "aml_autoscript.zip". Then use the button "Update". Confirmation.
