### ISSUE TITLE
I feel like I'm so close to LibreELEC-S905.aarch64-17.3_20170622.img on MXQ Pro....

### ISSUE THREAD

**Issue by javi404** [150balbes/Amlogic_s905#9]
150balbes,  thank you for all of your work.

I hope you can help or point me to correct info.

I have MXQ Pro 4k (S905)  p201 device

I am running stock MBOX android 5.1.1

I did the aml_autoscript update with success.

I flash SD card with LibreELEC-S905.aarch64-17.3_20170622.img downloaded from your yandex account.

I replaced dtb.bin with dtb.bin from your DTB folder in yandex. https://yadi.sk/d/srrtn6kpnsKz2/DTB/MXQ_Pro_4K

Device seems to be stuck in some boot loop.

it shows MXQ pro and flashes display and tries and tries again with no success.

If I remove SD card it boots from local flash to stock Android 5.1.1

Is there something I am doing wrong?

I also have the USB_Burning_Tool_v2.0.7.2_build2 from amlogic so I can flash images to the device local flash but I haven't had time to figure out what format the .img file it want's needs to be in.

I appreciate your help.

Let me know if there is something I can try or if I should reflash the whole device with a different firmware (to make sure bootloader is the correct version)

- J

**Comment by 150balbes** [comment]
On the website are outdated dtb files (for older versions of the images). Delete the file that you downloaded from the site. Try running without the dtb file. If the system is not run for 5-7 minutes without a dtb file then try to use the files that are on the media in the directory "dtb". Most likely you need a file with p201 in the title. Copy it to the root and rename to "dtb.img".

**Comment by javi404** [comment]
Got, it. I'll give that a try.


FYI I got the ubuntu mate kodi image running easy off of SD.

There is some performance issue that prevents kodi from running but if I can help you solve that it would be great.


Would be nice to have an ubuntu mate running on s905 + kodi.

I'm trying to move to 4k video soon. currently I'm watching movies via libreelec off of a raspberri pi B 2 which is nice but the s905 is better hardware as long as I can get the software to work.

I would also like to know how if possible to convert / create images that the amlogic flashing tool will accept so I can install images permanent to the on-board flash.

I'm going to analyze them soon to see what exactly is needed.

**Comment by javi404** [comment]
Also, who is this woman in test1.mp4 ? 

It didn't play good on the s905 box (I think I have a power supply problem because it froze twice) but I had to watch that video because I'm now in love.

**Comment by 150balbes** [comment]
Part of the answer is here.
https://forum.armbian.com/index.php?/forum/24-tv-boxes/
http://forum.khadas.com/t/3rd-party-ubuntu-rom-for-khadas-vim/
http://forum.puppyrus.org/index.php?PHPSESSID=18i9ebvacguq7hl8hs9p31kol7&board=175.0

> Also, who is this woman in test1.mp4 ?
maybe somebody's wife ......   :)

**Comment by javi404** [comment]
Thanks for the links, checking them out.
